export { default as IndexPage } from './IndexPage'
export { default as AddMemoryPage } from './AddMemoryPage'
export { default as AddMemorySuccessPage } from './AddMemorySuccessPage'
export { default as LoginPage } from './LoginPage'
export { default as MemoriesPage } from './MemoriesPage'
export { default as NotFoundPage } from './NotFoundPage'
export { SearchPage } from './search'
