name: Main
on: [push]
jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Integration testing
        uses: cypress-io/github-action@v1
        env:
          CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_APPLICATION_ID: ${{ secrets.REACT_APP_APPLICATION_ID }}
          REACT_APP_MASTER_KEY: ${{ secrets.REACT_APP_MASTER_KEY }}
          REACT_APP_SESSION_TOKEN: ${{ secrets.REACT_APP_SESSION_TOKEN }}
        with:
          start: npm start
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: cypress-videos
          path: /home/runner/work/memories-app/memories-app/cypress/videos
